name: fashion_shop_app
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_sticky_header: ^0.6.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  get: ^4.1.4
  get_storage: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/images/
